### ISSUE TITLE
Stuck on WakaTime Initializing... state

### ISSUE THREAD

**Issue by polatengin** [wakatime/vscode-wakatime#2]
I installed WakaTime extension yesterday, it stucks Initializing state forever.

**Comment by alanhamlett** [comment]
Fixed with v0.1.2.

**Comment by technbuzz** [comment]
What is the extension update process vscode, uninstall followed by reinstall?

**Comment by alanhamlett** [comment]
@technbuzz that works, I'm not sure when vscode auto-updates extensions.

**Comment by ltetzlaff** [comment]
if anybody else is still encountering this: make sure python is installed on your system

**Comment by WilRyan** [comment]
Add %WAKATIME_HOME% environment variable (Yes in i'm using windows..) to point to where your cfg file is.
